### ISSUE TITLE
Downloaded PDF with empty Data

### ISSUE THREAD

**Issue by srinuegs** [chuongtrh/html_to_pdf#1]
Steps for testing

1) Clone html_to_pdf repo
2) npm install 
3) node pdf.js
Then invoice.pdf generated with empty data

**Comment by chuongtrh** [comment]
hi @srinuegs 
Can you more clear about your situation? 
When you run _node pdf.js_ only create a PDF file **invoice.pdf**. It's no download PDF.

Also. I have added try/catch when creating pdf at commit [e420408](https://github.com/chuongtrh/html_to_pdf/commit/e420408765dbfb600205d956ec764f004fb7d74d)

**Comment by Suppasek** [comment]
I got empty PDF after run `node pdf.js`

**Comment by Suppasek** [comment]
using `await page.setContent(page.setContent(finalHtml))` works
