### ISSUE TITLE
Should use encodeURIComponent

### ISSUE THREAD

**Issue by floriaanpost** [chuongtrh/html_to_pdf#5]
Thank you for this example, it helped me a lot. 

I noticed a minor issue, I used a '#' in my HTML, but this breaks the example, because it should be URI encoded:

```js
await page.goto(`data:text/html,${encodeURIComponent(finalHtml)}`, {
    waitUntil: 'networkidle0'
});
```

**Comment by chuongtrh** [comment]
@floriaanpost Could you create pull request for this issue?

**Comment by chuongtrh** [comment]
Also, you can check pull request #3. It's updated but the document is not updated yet. Thanks
